name: Continous Integration

on: [workflow_call, push]


jobs:
    setup_github_repo:
        name: Setup Github Repository
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Setup SSH Private Keys
              run: |
                echo "${{ secrets.SSH_PRIVATE_KEY }}" > PRIVATE_KEY.pem
                chmod 600 PRIVATE_KEY.pem

            - name: Create SSH Directory
              run: |
                mkdir -p ~/.ssh

            - name: Configure Known Hosts
              run: |
                ssh-keyscan ${{ secrets.SERVER_IP}} >> ~/.ssh/known_hosts

            - name: Initalize repository
              run: |
                ssh -i PRIVATE_KEY.pem ubuntu@${{ secrets.SERVER_IP}} "cd ~/todo-app && git init"

            - name: Add Remote Repository
              run: |
                ssh -i PRIVATE_KEY.pem ubuntu@${{ secrets.SERVER_IP}} "cd ~/todo-app && git remote add origin ${{ secrets.REPO_GITHUB}}"

            - name: Pull from repository
              run: |
                ssh -i PRIVATE_KEY.pem ubuntu@${{ secrets.SERVER_IP}} " cd ~/todo-app && git pull origin master"


