name: Deployment

on:
    workflow_run: ["Setup Github Repository"]
    types:
        - completed

jobs:
    install-docker-compose:
        name: Install Docker Compose
        needs: [server_connection]
        runs-on: ubuntu-latest

        steps:
            - name: Update, install docker compose, adn pull from repository
              run: |
                ssh -i PRIVATE_KEY.pem ubuntu@${{ secrets.SERVER_IP}} "sudo apt-get update && sudo apt-get install -y docker-compose && cd todo-app-v1 && git pull origin master"