name: Continous Deployment

on:
  workflow_run: 
      workflows: ["Continous Integration"]
      branches: [master]
      types:
          - completed


jobs:
  conn_server:
    uses: ./.github.workflows/continous_integration.yml

  Deployment:
      name: Install Docker Compose
      needs: [conn_server]
      runs-on: ubuntu-latest

      steps:
          - name: Docker Compose Down
            run: |
              ssh -i PRIVATE_KEY.pem ubuntu@${{ secrets.SERVER_IP}} "cd ~/todo-app && sudo docker-compose down"

          - name: Docker Compose Up (Running in background)
            run: |
              ssh -i PRIVATE_KEY.pem ubuntu@${{ secrets.SERVER_IP}} "cd ~/todo-app && sudo docker-compose up -d"